version: '3'
services:
    zookeeper:
      image: confluent/zookeeper
      ports:
        - "2181:2181"

    kafka:
      image: wurstmeister/kafka:0.11.0.0
      ports:
        - "9092:9092"
      links:
      - zookeeper
      environment:
        KAFKA_ADVERTISED_HOST_NAME: kafka  #localhost or 127.0.0.1 or 10.0.75.1
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    kafka-manager:
      image: sheepkiller/kafka-manager:latest
      ports:
      - "9000:9000"
      links:
      - zookeeper
      - kafka
      environment:
        ZK_HOSTS: zookeeper:2181
        APPLICATION_SECRET: letmein
        KM_ARGS: -Djava.net.preferIPv4Stack=true

    subscription-api:
      build:
        context: ./subscription-api
      ports:
      - "8080:8080"
      links:
      - kafka
      environment:
        KAFKA_BOOTSTRAP: kafka:9092

    subscription-service:
      build:
        context: ./subscription-service
      ports:
      - "8090:8090"
      links:
      - kafka
      environment:
        KAFKA_BOOTSTRAP: kafka:9092
        AMAZON_ACCESS_KEY: "test"
        AMAZON_SECRET_KEY: "test"

    subscription-email:
      build:
        context: ./subscription-email-service
      ports:
      - "8070:8070"
      links:
      - kafka
      environment:
        KAFKA_BOOTSTRAP: kafka:9092




